<a id='Model_Building'></a>
## Model Building

As this is classification problem. So, we can apply following algorithms.
* Logistic Regression
* Random Forest
* Support Vector Machine
* K Nearest Neighbour

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('dataset/final_data.csv', index_col = 'issue_d')

In [4]:
df.head()

inq_last_6mths  recoveries  annual_inc  loan_amnt  int_rate  \
issue_d                                                                   
2007-06-01               0         0.0     22000.0     7500.0     13.75   
2007-07-01               0         0.0    150000.0     5000.0      7.43   
2007-07-01               0         0.0    125000.0     5750.0      7.43   
2007-07-01               2         0.0     40000.0     5000.0      7.43   
2007-07-01               2         0.0     20000.0     1200.0     11.54   

            emp_length  out_prncp  total_pymnt  collection_recovery_fee  \
issue_d                                                                   
2007-06-01           1        0.0      9194.98                      0.0   
2007-07-01           8        0.0      5174.17                      0.0   
2007-07-01          10        0.0      6421.50                      0.0   
2007-07-01           6        0.0      5593.39                      0.0   
2007-07-01           1        0.0      1425.37                      0.0   

            default_ind  ...  sub_grade_G4  sub_grade_G5  \
issue_d                  ...                               
2007-06-01            0  ...             0             0   
2007-07-01            0  ...             0             0   
2007-07-01            0  ...             0             0   
2007-07-01            0  ...             0             0   
2007-07-01            0  ...             0             0   

            home_ownership_Other  home_ownership_Own  home_ownership_Rent  \
issue_d                                                                     
2007-06-01                     0                   1                    0   
2007-07-01                     0                   0                    0   
2007-07-01                     0                   0                    0   
2007-07-01                     0                   0                    1   
2007-07-01                     0                   0                    1   

            verification_status_Verified  purpose_credit_card  \
issue_d                                                         
2007-06-01                             0                    0   
2007-07-01                             0                    0   
2007-07-01                             0                    0   
2007-07-01                             0                    0   
2007-07-01                             0                    1   

            purpose_debt_consolidation  pub_rec_Good  initial_list_status_w  
issue_d                                                                      
2007-06-01                           1             1                      0  
2007-07-01                           0             1                      0  
2007-07-01                           1             1                      0  
2007-07-01                           0             1                      0  
2007-07-01                           0             1                      0  

[5 rows x 53 columns]

In [5]:
# Deviding Dataset into x and y
y = df['default_ind']
x = df.drop('default_ind', axis=1)

## Train Test Split

We are using 'issue_d' column to divide the data into train and test split.

* Train Data will consists => June 2007 - May 2015
* Test Data will consists => June 2015 - Dec 2015

REF : https://stackoverflow.com/questions/37532098/split-dataframe-into-two-on-the-basis-of-date

In [6]:
# Splitting Dataframe according to Date as given in problem statement
train_dataset = df['2007-06-01':'2015-05-1']
test_dataset = df['2015-05-1':]
print('Train Dataset:',train_dataset.shape)
print('Test Dataset:',test_dataset.shape)

Train Dataset: (598978, 53)
Test Dataset: (256991, 53)


In [7]:
# Devide Dataset into Train and Test
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_dataset[x.columns] , test_dataset[x.columns] , train_dataset['default_ind'] , test_dataset['default_ind']
print("Dataset with Shape :\nx_train ",x_train.shape,"\ny_train ",y_train.shape ,"\nx_test ",x_test.shape, "\ny_test ",y_test.shape)

Dataset with Shape :
x_train  (598978, 52) 
y_train  (598978,) 
x_test  (256991, 52) 
y_test  (256991,)


In [9]:
y_test.value_counts()

0    256680
1       311
Name: default_ind, dtype: int64

In [10]:
# Libraries for Validation of models
from sklearn.metrics import confusion_matrix

## Logistic Regression

In [12]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(solver='lbfgs').fit(x_train,y_train)
logistic_predict = logistic_model.predict(x_test)

In [13]:
# Checking Accuracy
logistic_conusion_matrix = confusion_matrix(y_test,logistic_predict)
logistic_conusion_matrix

array([[256572,    108],
       [    68,    243]], dtype=int64)

## Random Forest

In [14]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators = 100, criterion='gini')
rf_model = rf_model.fit(x_train, y_train)
rf_model_predict = rf_model.predict(x_test)

In [15]:
# Checking Accuracy
logistic_conusion_matrix = confusion_matrix(y_test,logistic_predict)
logistic_conusion_matrix

array([[256572,    108],
       [    68,    243]], dtype=int64)

## SVM - Support Vector Machine

In [ ]:
# SVM - Support Vector Machine
from sklearn import svm
svm_model = svm.SVC(kernel='rbf', gamma = 'scale')
svm_model = svm_model.fit(x_train,y_train)
svm_predict = svm_model.predict(x_test)

In [ ]:
# Checking Accuracy
svm_conusion_matrix = confusion_matrix(y_test, svm_predict)
svm_conusion_matrix

## KNN - K Nearest Neighbour

In [16]:
# KNN - K Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model = knn_model.fit(x_train,y_train)
knn_predict = knn_model.predict(x_test)

In [17]:
# Checking Accuracy
knn_conusion_matrix = confusion_matrix(y_test,knn_predict)
knn_conusion_matrix

array([[250905,   5775],
       [    58,    253]], dtype=int64)

In [19]:
# Choosing a K Value with Elbow method
error_rate = []
for i in range(3,30):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,y_train)
    pred_i = knn.predict(x_test)
    error_rate.append(np.mean(pred_i != y_test))

In [21]:
import matplotlib.pyplot as plt

In [22]:
plt.figure(figsize=(10,6))
plt.plot(range(3,30),error_rate,color='blue', linestyle='dashed', marker='o', markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

Text(0, 0.5, 'Error Rate')

In [ ]:
knn_model2 = KNeighborsClassifier(n_neighbors=7)
knn_model2 = knn_model.fit(x_train,y_train)
knn_predict2 = knn_model.predict(x_test)

In [ ]:
# Checking Accuracy
knn_conusion_matrix = confusion_matrix(y_test,knn_predict2)
knn_conusion_matrix

<a id='Model_Evaluation'></a>
## Model Evaluation

* Confusion Matrix
* Accuracy
* Precision
* Recall
* F1 Score

<a id='conclusion'></a>
## Conclusion

With references of the above models and model evaluations we can say that model is giving the best solution for the given 
problem.